services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hl2
      POSTGRES_USER: hl2
      POSTGRES_PASSWORD: hl2pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"          # снаружи 5433, внутри 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=1000

  backend:
    build:
      context: ./1.main
      dockerfile: Dockerfile.main
    container_name: backend
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "${LIMITS_CPU}"
          memory: ${LIMITS_MEM}
        reservations:
          cpus: "${RESERV_CPU}"
          memory: ${RESERV_MEM}
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SERVER_TOMCAT_MAX_THREADS: ${LIMITS_THREADS}
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hl2
      SPRING_DATASOURCE_USERNAME: hl2
      SPRING_DATASOURCE_PASSWORD: hl2pass

  additional:
    build:
      context: ./2.additional
      dockerfile: Dockerfile.additional
    container_name: additional
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256m
    ports:
      - "8081:8081"
    environment:
      MAIN_SERVICE_URL: http://backend:8080