### build stage 
FROM gradle:jdk25-ubi10 AS build

WORKDIR /app

COPY . .

RUN gradle bootJar -x test --no-daemon

RUN mv build/libs/*[!plain].jar build/libs/app.jar

### run stage
FROM eclipse-temurin:25-jdk-ubi10-minimal

WORKDIR /app

RUN groupadd -r appgroup && useradd -r -g appgroup appuser
USER appuser

COPY --from=build /app/build/libs/app.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
