version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    user: ${POSTGRES_USER}

volumes:
  pgdata: