services:
  main:
    image: git.dyakov.space/dyakovli/hl-main:1.0
    container_name: ${MAIN_URL}
    extra_hosts:
      - "${KAFKA_URL}:${KAFKA_IP}"
    deploy:
      resources:
        limits:
          cpus: "${LIMITS_CPU}"
          memory: ${LIMITS_MEM}
        reservations:
          cpus: "${RESERV_CPU}"
          memory: ${RESERV_MEM}
    ports:
      - "8080:${MAIN_PORT}"
    env_file:
      - .env
    environment:
      SERVER_TOMCAT_MAX_THREADS: ${LIMITS_THREADS}
      SPRING_JPA_SHOW_SQL: "false"

  additional:
    image: git.dyakov.space/dyakovli/hl-additional:1.0
    container_name: ${ADDITIONAL_URL}
    depends_on:
      - main
    deploy:
      resources:
        limits:
          cpus: "${LIMITS_CPU}"
          memory: ${LIMITS_MEM_A}
    ports:
      - "8081:${ADDITIONAL_PORT}"
    env_file:
      - .env
    environment:
      MAIN_SERVICE_URL: http://${MAIN_URL}:${MAIN_PORT}

