apiVersion: apps/v1
kind: Deployment
metadata:
  name: additional
  namespace: dyakovli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: additional
  template:
    metadata:
      labels:
        app: additional
    spec:
      imagePullSecrets:
        - name: gitea-secret
      containers:
        - name: additional
          image: git.dyakov.space/dyakovli/hl-additional:1.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret       # ← было слеплено с startupProbe
          startupProbe:               # ← было съехавшее выравнивание
            httpGet:
              path: /health
              port: 8081
            failureThreshold: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            periodSeconds: 10
            failureThreshold: 2
            timeoutSeconds: 3
