apiVersion: apps/v1
kind: Deployment
metadata:
  name: additional
  namespace: dyakovli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: additional
  template:
    metadata:
      labels:
        app: additional
    spec:
      imagePullSecrets:
        - name: gitea-secret
      containers:
        - name: additional
          image: git.dyakov.space/dyakovli/hl-additional:1.0
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
