apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dyakovli
data:
  DB_HOST: "10.60.3.9"
  DB_PORT: "5433"
  POSTGRES_DB: "hl2?currentSchema=hl2"
  SPRING_JPA_SHOW_SQL: "false"
  SERVER_TOMCAT_MAX_THREADS: "200"
  ADDITIONAL_URL: "additional"
  ADDITIONAL_PORT: "8081"
  MAIN_URL: "main-svc"
  MAIN_PORT: "8080"
  MAIN_SERVICE_URL: "http://main-svc:8080"
  KAFKA_URL: "10.60.3.12"
  KAFKA_PORT: "9094"
  KAFKA_IP: "10.60.3.13"
  KAFKA_CONSUMER: "test-group-1"
  KAFKA_TOPIC: "hl02"
  KAFKA_CONCURRENCY: "1"
  LIMITS_THREADS: "200"
