apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dyakovli
type: Opaque
data:
  # echo -n 'your_password' | base64
  POSTGRES_USER: <BASE64_ENCODED_USER>
  POSTGRES_PASSWORD: <BASE64_ENCODED_PASSWORD>
