apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
  namespace: dyakovli
type: kubernetes.io/dockerconfigjson
data:
  # Создать вручную командой:
  # kubectl create secret docker-registry gitea-secret \
  #   --docker-server=git.dyakov.space \
  #   --docker-username=<USERNAME> \
  #   --docker-password=<PASSWORD> \
  #   --namespace=dyakovli
  .dockerconfigjson: <BASE64_ENCODED_DOCKERCONFIG>
