apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  namespace: dyakovli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      imagePullSecrets:
        - name: gitea-secret
      hostAliases:
        - ip: "10.60.3.12"
          hostnames: ["hl14.zil"]
        - ip: "10.60.3.13"
          hostnames: ["hl15.zil"]
      containers:
        - name: main
          image: git.dyakov.space/dyakovli/hl-main:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
