apiVersion: v1
kind: Service
metadata:
  name: main-nodeport
  namespace: dyakovli
spec:
  type: NodePort
  selector:
    app: main
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
