### build stage 
FROM gradle:jdk25-corretto AS build

WORKDIR /app

COPY . .

RUN gradle bootJar -x test --no-daemon

RUN mv build/libs/*[!plain].jar build/libs/app.jar

### run stage
FROM eclipse-temurin:25-jre-alpine

WORKDIR /app

RUN addgroup -S appgroup && adduser -S -G appgroup appuser
USER appuser

COPY --from=build /app/build/libs/app.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]
